### ISSUE TITLE
Public Slides Link Problem

### ISSUE THREAD

**Issue by vanessa-nr** [dlab-berkeley/IRB-Fundamentals#7]
The link to the public slides leads to a slide deck that was moved into the trash folder, so the link needs to be updated. There appears to be a new IRB slide deck on google drive.

**Comment by aculich** [comment]
@vanessa-nr can you please provide the google drive link here? Thanks!

**Comment by aculich** [comment]
Looks like @pssachdeva modified links and copied/trashed files yesterday, so I'm re-assigning this.

**Comment by pssachdeva** [comment]
Closed by #8
